name: Build and Push Docker images

on:
  pull_request:
    branches: ["main", "dev"]
  push:
    branches: ["main", "WW-113"]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      sql-db:
        image: wisdomwork/sql:latest
        env:
          MYSQL_DATABASE: codee
          # So you don't have to use root, but you can if you like
          MYSQL_USER: admin
          # You can use whatever password you like
          MYSQL_PASSWORD: Wisdomworks.33
          # Password for root access
          MYSQL_ROOT_PASSWORD: Wisdomworks.33
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      nosql-db:
        image: wisdomwork/mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: Wisdomworks.33
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/codee
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: Wisdomworks.33
          SPRING_DATA_MONGODB_URI: mongodb://admin:Wisdomworks.33@localhost/?retryWrites=true&w=majority
          SPRING_DATA_MONGODB_DATABASE: codee
        run: mvn -B package --file pom.xml

  build-and-push:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/codee-be:latest
